### ISSUE TITLE
Crash on iOS8

### ISSUE THREAD

**Issue by PPPiotr** [Kekiiwaa/Localize#10]
On iOS 8 app crashes when You change the language after some ViewControllers was destroyed. 

It crashes on line:
`NotificationCenter.default.post(name: Notification.Name(rawValue: LocalizeChangeNotification), object: nil)`
In method: 
`public func update(language:Languages) -> Void`
Of class:
`LocalizeCommonProtocol`

It most likely because of not removing the observer from NotificationCenter that are added in `awakeFromNib` methods in extensions of UIControlls in file `LocalizeExtensions`. 

This is not needed for iOS9 and above. 
[http://useyourloaf.com/blog/unregistering-nsnotificationcenter-observers-in-ios-9/](url)

**Comment by andresilvagomez** [comment]
@PPPiotr thanks, I'll work on that
