### ISSUE TITLE
Localize Storyboard on the fly

### ISSUE THREAD

**Issue by embassem** [Kekiiwaa/Localize#9]
localize storyboard on the fly using Storyboard String file Not working

**Comment by andresilvagomez** [comment]
@embassem Hi, could you tell me, when you referred to Storyboard String, is a file with storyboard ids? same to.

/* Class = "UILabel"; text = "app.label"; ObjectID = "BBe-T0-9G7"; */
"BBe-T0-9G7.text" = "app.label";

**Comment by embassem** [comment]
i mean is  localize  bundle and layout  on the fly  so the LTR layout can be RTL . if change lang to ar as example .  
not  just strings .

**Comment by embassem** [comment]
check this repo 
https://github.com/cmaftuleac/BundleLocalization
